### PR TITLE
Mark package as abandoned

### PR DESCRIPTION
**Pull request by core23**
Refs: https://github.com/sonata-project/dev-kit/issues/1669

### CODE REVIEW

**Comment by jordisala1991** [comment]
We didnt discus a lot about this one. Does it make sense? I think this library is used by some people but dont know if there is a good replacement

**Comment by jordisala1991** [comment]
Also this one is used on SonataUserBundle and we keep that one. IMO we should not abandon this one yet

**Comment by core23** [comment]
There are some critical issue for this project and there are no active developers who want to fix this.

**Comment by VincentLanglet** [comment]
I don't know about this one.

Issues are regularly created and we're using it on the UserBundle.

But on the other side no core members are using it/working on it.
And that's kinda the definition of abandoned. We're not saying it's deprecated, just that nobody work on it.

But if we abandoned it, an issue should be created and pinned like https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/600

**Comment by core23** [comment]
Issue: #309

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — COMMENTED** [review]
I think we should wait until we figure out if we want to maintain the integration with SonataUserBundle or not to abandon it or not.

**Comment by VincentLanglet** [comment]
> I think we should wait until we figure out if we want to maintain the integration with SonataUserBundle or not to abandon it or not.

I think we can consider this package as abandoned. We're not really following the issues or working on improving this lib.
The integration could be deprecated from SonataUserBundle and lead to a simpler SonataUserBundle repository.

wdyt @sonata-project/contributors ?

**Comment by jordisala1991** [comment]
I dont know, to me it depends if there are alternatives.

**Comment by VincentLanglet** [comment]
> I dont know, to me it depends if there are alternatives.

I would recommend to
- fork
- use another lib
- use own implementation

To me the question is "Do we currently maintain this library ?" and looking at the issue and the activity I would say no.

Still marking the lib as abandoned doesn't forbid to use it, it's just more honest about the status of it.

**Comment by jordisala1991** [comment]
Given this package consist on 4 classes and 1 exception class. And given we didnt had enough time to take a look at user bundle. And given this package is used (probably no by a lot of people, but more used for sure than other bundles we deprecated). I would prefer waiting to see how it goes when we deprecate all the big ones and dev kit doesnt care more for them, and we finish the migration to Sonata 4 to decide.

**Comment by core23** [comment]
We should not advertise the usage of this lib as long as there are potential security issues (https://github.com/sonata-project/GoogleAuthenticator/issues/288) and we won't try to fix this.

**Comment by jordisala1991** [comment]
Those are fixable things. As I said on my previous message... can we wait? :)

**Comment by jordisala1991** [comment]
Maybe a better approach is to integrate or document how to integrate with this: https://github.com/scheb/2fa

Do you know another alternative?

**Comment by jordisala1991** [comment]
I have read this docs: https://symfony.com/bundles/SchebTwoFactorBundle/current/index.html

And it looks good:
- In the official docs of Symfony
- Looks updated enough to work with new authenticated system
- It works with several systems
- We should we able to provide some docs and not a direct integration, which is nice.

**Review by jordisala1991 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Done in https://github.com/sonata-project/GoogleAuthenticator/pull/336

**Pull request closed without merging**
