### PR TITLE
Added a very simple test for encoding and decoding of bits

### PR DESCRIPTION
**Pull request by iltar**
Created a test to verify if the behavior of the encoding and decoding is what we expect it to be, without loss of information and if bogus input is returned early as empty string. This PR won't generate a lot of coverage nor cover edge cases.

### CODE REVIEW

**Comment by greg0ire** [comment]
@OskarStark a PR can't be patch and pedantic at the same time. This does not warrant a new release, so... pedantic

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by greg0ire** [comment]
Thanks @iltar !

**Comment by OskarStark** [comment]
> @OskarStark a PR can't be patch and pedantic at the same time. This does not warrant a new release, so... pedantic

oops sorry, first i checked patch and then i used pedantic, but didn't uncheck the patch label...

**Pull request merged**
