### PR TITLE
Implemented constant time code comparison

### PR DESCRIPTION
**Pull request by zerkms**
I am targetting this branch, because it is backward compatible

## Changelog

```markdown

### Security
- Implemented constant time codes comparison
```

## Subject

It implements the equality comparison of the passed and generated code in constant time. It is a de-facto security standard these days in case when user's input is compared with secret (or derived from secret) data.

### CODE REVIEW

**Comment by OskarStark** [comment]
PLease fix PR headert

**Comment by zerkms** [comment]
@OskarStark indeed. Like that?

**Comment by OskarStark** [comment]
> @OskarStark indeed. Like that?

Yes, thank you!
Could you provide a test for the new method?

**Comment by OskarStark** [comment]
@greg0ire or no test because it is private?

**Comment by OskarStark** [comment]
@zerkms please have a look at StyleCI!

**Comment by greg0ire** [comment]
> @greg0ire or no test because it is private? 

private methods are a bit harder to test, but should absolutely be tested nonetheless…

**Comment by greg0ire** [comment]
Note that there seems to already be an (indirect, of course) [test](https://github.com/sonata-project/GoogleAuthenticator/blob/1.x/tests/GoogleAuthenticatorTest.php#L39) for the method.

**Comment by zerkms** [comment]
@OskarStark not sure what that means

And we definitely should not test not public methods directly: unit tests are about behaviour not implementation details.

**Comment by greg0ire** [comment]
> It does not exactly state what I've made wrong, so I must admit I have no clue what I am supposed to fix (and how).

Yes it does. Click the "Details" link, you will see a patch you can apply to fix the problem (which is, in this occurence, not having private methods at the end of the file).

> And we definitely should not test non-public methods directly: unit tests are about behaviour not implementation details.

:+1:

**Comment by zerkms** [comment]
> Yes it does. Click the "Details" link, you will see a patch you can apply to fix the problem (which is, in this occurence, not having private methods at the end of the file).

I've seen it but I just could not believe someone would deliberately move an auxiliary method so far from its context (the only place where it is used).

**Comment by greg0ire** [comment]
Yeah I'm not a huge fan of this rule either, but...

**Comment by greg0ire** [comment]
LGTM! @OskarStark , final review and merge?

**Comment by OskarStark** [comment]
Thank you @zerkms 

@greg0ire `minor` ?

**Comment by greg0ire** [comment]
To quote @zerkms from memory, "there is no API change, so patch"

**Comment by OskarStark** [comment]
👍

**Pull request merged**
