### PR TITLE
Drop old versions of dependencies

### PR DESCRIPTION
**Pull request by greg0ire**
Only test dependencies were touched, so this is pedantic.

### CODE REVIEW

**Comment by greg0ire** [comment]
might as well

**Comment by greg0ire** [comment]
Should I do the same for `sllh/php-cs-fixer-styleci-bridge`? And if yes, `^2.1.1` or `^2.1`… not sure if this makes much sense after all… or even if this PR does.

**Comment by core23** [comment]
^2.1 should be fine enough if we depend on new fixers

**Comment by greg0ire** [comment]
Done

**Comment by greg0ire** [comment]
And after this PR, I think we should release 2.0.

**Comment by core23** [comment]
Before releasing a new major release, we should have a look at: https://github.com/sonata-project/dev-kit/issues/184

**Comment by greg0ire** [comment]
Only the vendor prefix is major IMO.

**Pull request merged**
