### PR TITLE
Use mt_rand over rand, when repeatedly calling in quick succession.

### PR DESCRIPTION
**Pull request by kevintweber**
When calling rand() in a loop, you don't actually get much randomness.  It would be better to call mt_rand() in this situation.

I hope this helps.

### CODE REVIEW

**Comment by beberlei** [comment]
@rande Couldn't we use openssl random bytes here or use the symfony abstraction to get a true random string? This code gives me the creeps and makes using this library rather insecure.

**Comment by rande** [comment]
@beberlei feel free to send a PR with the related documentations: BC break if any, tests .

Please note, this project is a fork of https://github.com/chregu/GoogleAuthenticator.php/blob/master/lib/GoogleAuthenticator.php which wasn't composer ready.

**Comment by core23** [comment]
Please rebase @kevintweber

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
