### PR TITLE
Use different QR generation site as Google Chart API no longer supports QR codes

### LINKED ISSUE #136: Google Charts API is deprecated and not available since March 19, 2019
## Subject
Problem with getting QR code from https://chart.googleapis.com/chart?

## Actual results
502 error

### PR DESCRIPTION
**Pull request by netniV**
## Use different QR generation site as Google Chart API no longer supports QR codes

This is a fix for the #136 issue

I am targeting this branch, because Google depreciated their old API

Closes #136 

## Changelog

```markdown
### Fixed
- Invalid/deprecated Google URL for QR code generation
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Hey @netniV 👋 

Thank you for your contribution, can you please change travis and fix the failing tests?

Thank you!

**Comment by netniV** [comment]
Sure, wondered what you meant at first then I realised you have tests that are using these and travis is moaning that they don't match (correctly) 👍

**Comment by netniV** [comment]
So I updated the tests, but yet Travis is still not happy for some reason, did I miss something?

**Comment by netniV** [comment]
Never mind, spotted it, I only changed one of the tests not all of them.

**Comment by kunicmarko20** [comment]
@olenichphp @jgaranae @anomis66 can someone test this and confirm the fix

**Comment by netniV** [comment]
Thanks for the review @OskarStark.  Should all be sorted now.

**Pull request merged**
